server:
  port: 8080
spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:clickhouse://localhost:8123/?database=default&socket_timeout=60000
##    username: default
##    password:
#    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000
#      idle-timeout: 60000
#  jpa:
#    properties:
#      hibernate:
#        dialect: ru.yandex.clickhouse.ClickHouseDialect